shardtree: Add `Reference` retention to make it possible to limit pruning.
zcash/incrementalmerkletree pull request #105
Opened 2024-05-21 23:27 UTC by nuttycom

Related to zcash/librustzcash#1398

2024-05-28 18:31 UTC, str4d requested changes
Reviewed 6769a75eb38c3672f122c06261c1d17bc9069df4.

2024-05-28 18:31 UTC, str4d commented on shardtree/src/lib.rs
> +                    Some(pos) if pos >= subtree.root_addr.max_position() => {
How can this be greater? I don't think it can, so it doesn't matter if this is just `==`, but I can see why you might make this `>=` for semantic correctness. Add a comment explaining.

2024-05-28 18:31 UTC, str4d commented on shardtree/src/lib.rs
> +            // with `Reference` marking.
```suggestion
            // with the specified marking.
```

2024-05-28 19:17 UTC, nuttycom commented on shardtree/src/prunable.rs
> +        const REFERENCE = 0b00000100;
There should be no change necessary to prevent pruning, because a node is only prunable if both it and its sibling are prunable, and the `REFERENCE`'d branch will not be prunable.

2024-05-28 19:19 UTC, nuttycom commented on shardtree/src/lib.rs
> +                Retention::Ephemeral | Retention::Reference => Ok(()),
The empty tree has no retention whatsoever (it does not have `Ephemeral` retention prior to this change.) Similarly, parent nodes do not have explicit retention; pruning of a parent occurs when both child nodes are prunable.

2024-05-28 20:25 UTC, nuttycom commented on shardtree/src/prunable.rs
> -                                assert_eq!(*pos, root_addr.max_position());
You can be clearing the `CHECKPOINT` retention flag from a partially complete tree that was inserted beneath a `Pruned` node, in which case this assertion is violated.

2024-05-28 22:48 UTC, str4d commented on shardtree/src/prunable.rs
> +            (Tree(Node::Pruned), Tree(Node::Nil)) => Tree(Node::Pruned),
There are no _existing_ annotations on `Nil` or `Pruned` nodes. But this here is checking what `left` and `right` are, and in the default case _creates_ a parent that wraps them and has annotation `ann`.

Thus, if this method is called with `ann.is_some()` and children that are `Nil` or `Pruned`:
- We lose `ann` by merging these children into a `Pruned` parent.
- We possibly lose information about the fact that one of the children was `Nil`, not `Pruned`.

2024-05-28 23:46 UTC, nuttycom commented on shardtree/src/lib.rs
> +            Node::Nil | Node::Pruned => {
This is being used to compute values within the "cap" of the tree - if information is missing, it will simply be recomputed by walking down to the roots of the subtree shards, and it will either succeed (because it has all the shard roots needed) or it will fail. So I believe that this is correct for both empty tree states in this particular context.

2024-05-29 00:55 UTC, nuttycom commented on shardtree/src/prunable.rs
> +            (Tree(Node::Pruned), Tree(Node::Nil)) => Tree(Node::Pruned),
Ah, yeah, that's a good point; if a left node is pruned and a right is `Nil` or vice versa, we do want to construct a new `Parent` node.

2024-05-29 00:56 UTC, nuttycom commented on shardtree/src/prunable.rs
> +            (Tree(Node::Pruned), Tree(Node::Nil)) => Tree(Node::Pruned),
It might actually make sense to check `ann` against the computed value for conflict when handling the current `leaf` cases. I'll make that change.

2024-05-30 14:03 UTC, str4d approved these changes
utACK d40e178f8d0469b0cf0fc4d027a23c5e7581961f with suggestion.

2024-05-30 14:06 UTC, str4d approved these changes
Re-utACK 93512976ddfeb1e1513191c1239f9c386593a02d

2024-05-30 14:57 UTC, merged