shardtree: Use annotated parent nodes with empty children for inserted frontier ommers.
zcash/incrementalmerkletree pull request #107
Opened 2024-06-26 15:31 UTC by nuttycom

2024-06-26 15:46 UTC, nuttycom commented on shardtree/src/prunable.rs
> -                assert!(new_tree.max_position() >= max_position);
The removal of this assertion is intentional; given the way that `shardtree` was used prior to this PR, it is not possible to determine whether a `Node::Leaf` value in a persisted tree was present as a pruned subtree root, or because of direct insertion as a shard root or the ommer of an inserted frontier. In general, the maximum position of populated nodes within a subtree should only be used when considering the maximum inserted position of the overall tree.

2024-06-27 18:30 UTC, str4d requested changes
Reviewed 68935c8677a8e25dd713d0bae846dd4a1369e926.

2024-06-27 18:30 UTC, str4d commented on shardtree/src/tree.rs
> +            Node::Parent { right, .. } => right.is_full(),
Hmm, this definition of `is_full` is a little confusing.
- In the abstract context, "append" is not well-defined, as leaves can be added anywhere we have a `Node::Nil`; tree "fullness" would mean "absence of any `Node::Nil`s". In the concrete context, what we specifically care about is append-on-the-right.
- `Node::Nil` in the abstract context means "empty tree", implying that we can abstractly add nodes below it. But in the concrete context, it means "we have no information", and so it _might_ be the case that no additional nodes can be appended to this tree.

I think it would be clearer if this was named `is_definitely_full_on_right`, and the documentation clarified that returning `false` doesn't mean that we can definitely add more nodes on the right to the tree that this `Tree` represents, only that we have not observed it to be full.

2024-06-27 18:30 UTC, str4d commented on shardtree/src/lib.rs
> -                    // If the subtree is full, then construct a successor tree.
Keep this comment?

2024-06-27 18:30 UTC, str4d commented on shardtree/src/lib.rs
> +                    subtree.append(value, retention)?
I _think_ this is well-defined in the context of `!is_definitely_full_on_right()` (nee `!is_full()`) when given the context of this `append()` method (namely that all right-most `Nil` nodes in the last subtree must correspond to actually-absent data, which can only be ensured by the caller).

2024-06-27 18:31 UTC, str4d commented
Also, fix the clippy lints :)

2024-06-27 18:49 UTC, nuttycom commented on shardtree/src/tree.rs
> +            Node::Parent { right, .. } => right.is_full(),
I don't think that `definitely` adds anything. Maybe it would be better to name this `can_append` and invert the sense.

2024-06-27 18:58 UTC, nuttycom commented on shardtree/src/tree.rs
> +            Node::Parent { right, .. } => right.is_full(),
I had originally documented this as "no new nodes can be appended without introducing a new parent node with this node as the left child" but then decided that that was excessive; *this* tree can't have anything appended to it if it's full.

2024-06-27 20:05 UTC, nuttycom commented on shardtree/src/legacy.rs
> +                    true,
It occurs to me now that, when inserting a frontier into a tree, what should actually happen is that the observed-ness of the root node being replaced should be propagated downward; this works better than the caller of `from_frontier_parts` having to decide what's appropriate (because they may not be able to know) and this then works well with the update to use a `Parent` with `Nil` children at the root of each shard; once it's been fully scanned and turned into a `Leaf`, subsequent `Frontier` insertions should also use `Leaf` nodes for the inserted ommers.

2024-06-28 16:51 UTC, nuttycom commented on shardtree/src/prunable.rs
> +                        Tree::empty_annotated(Some(Arc::new(left)))
As discussed in pairing, the caller can't know whether ommers_fully_observed is true or not, so we're going back to the representation that uses `Leaf` for all terminal nodes for which the value is known.

2024-06-28 19:14 UTC, str4d approved these changes
utACK 192cb3ffda7b5fa018d8efa89551a7376275e4f8

2024-06-28 19:30 UTC, merged