shardtree: Significantly rework handling of checkpoint depths and truncation operations.
zcash/incrementalmerkletree pull request #115
Opened 2024-09-26 20:56 UTC by nuttycom

2024-09-26 23:32 UTC, daira commented on incrementalmerkletree-testing/src/complete_tree.rs
> +        if self.checkpoints.len() > depth {
Shouldn't it be valid to rewind by exactly the number of checkpoints?

2024-09-26 23:34 UTC, daira commented on incrementalmerkletree-testing/src/complete_tree.rs
> +    fn root(&self, checkpoint_depth: Option<usize>) -> Option<H> {
Document this.

2024-09-26 23:42 UTC, nuttycom commented on incrementalmerkletree-testing/src/complete_tree.rs
> +        if self.checkpoints.len() > depth {
Depth is treated as a (reverse-ordered) 0-based index, so it must be less than the length.

2024-09-26 23:54 UTC, str4d reviewed
Reviewed 0c01af944a3b0b7a0c9c4e4ffbd1b2aacba3fc9f (the first commit), flushing comments.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/lib.rs
> +    /// Returns `None` if a checkpoint depth is provided but if there are not enough checkpoints
```suggestion
    /// Returns `None` if a checkpoint depth is provided but there are not enough checkpoints
```

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/CHANGELOG.md
> +- `incrementalmerkletree_testing::Tree::checkpoint_count`
Nit: this is a change to a trait, as it doesn't have a provided implementation.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/lib.rs
> +    /// Obtains the root of the Merkle tree at the specified checkpoint depth by hashing against
The trait uses the word "depth" to mean two things:
- The vertical distance below the root that the tree extends.
- The horizontal distance to the right of the most recent checkpoint through the tree's checkpoints.

It would be nice to find an alternative word for the latter, or clarify what "checkpoint depth" means in the few places it gets used.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/lib.rs
> +    /// Rewinds the tree state to the checkpoint at the specified depth.
This is what triggered my prior comment: "at the specified depth" sounds like a vertical measure (e.g. at the root of some subtree below the tree root) rather than the intended horizontal measure.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/lib.rs
> +    /// discarded.
The first and second sentences seem (to me) to duplicate information, but it's past midnight and I can't think of better wording.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/complete_tree.rs
> +            if u64::from(position) >= u64::try_from(leaves_len).unwrap() {
This unwrap seems to not match the documentation for `Tree::witness`; if `leaves_len.is_none()` then "no checkpoint is available at the specified depth". If this is now a case that `Tree` impls should panic, update the trait method documentation.

2024-09-26 23:54 UTC, str4d commented on incrementalmerkletree-testing/src/complete_tree.rs
> +                    self.marks.remove(pos);
To clarify, this is correct because the checkpoint's `marked` field stores changes _after_ that checkpoint? (The checkpoint is acting here as the potato box.)

2024-09-27 02:51 UTC, nuttycom commented on incrementalmerkletree-testing/src/complete_tree.rs
> +            if u64::from(position) >= u64::try_from(leaves_len).unwrap() {
That unwrap is for the `u64::try_from`.

2024-09-27 02:52 UTC, nuttycom commented on incrementalmerkletree-testing/src/complete_tree.rs
> +                    self.marks.remove(pos);
Correct.

2024-09-27 03:19 UTC, str4d requested changes
Reviewed 818941800e7553fbc86c8af1f7a31df20e18c695.

2024-09-27 03:19 UTC, str4d commented on shardtree/src/lib.rs
>      pub fn witness_at_checkpoint_depth(
AFAICT this change (specifically the 1-indexing to 0-indexing) is not documented in the changelog. Unlike `witness_at_checkpoint_id` there's no method API change because this method returns an error instead of `Ok(None)` if the checkpoint does not exist.

The API difference separately seems like an API consistency bug? If it is intentional, document the difference (and when the distinction should be made use of by downstream crate users) in both methods' documentation (cross-referencing each other), for both pairs (caching and non).

2024-09-27 03:19 UTC, str4d commented on shardtree/src/lib.rs
>          checkpoint_depth: usize,
Ditto: the change of this method from 1-indexing to 0-indexing is not documented in the changelog.

2024-09-27 03:20 UTC, str4d commented on incrementalmerkletree-testing/src/complete_tree.rs
> +            if u64::from(position) >= u64::try_from(leaves_len).unwrap() {
Ah, I missed the trailing `?` on the `self.leaves_at_checkpoint_depth()` call.

2024-09-27 04:23 UTC, nuttycom commented on shardtree/src/lib.rs
>      pub fn witness_at_checkpoint_depth(
The API difference here was intentional, but I could be convinced to make the two consistent. My rationale was that requesting a specific checkpoint identifier is akin to requesting a specific map key, whereas requesting a witness using a checkpoint depth can either fail because no checkpoint is available, or because the checkpoint is for the empty tree (and consequently a request for a witness as of that tree state is nonsensical.) However, maybe those two kinds of errors should not be conflated.

2024-09-27 12:47 UTC, str4d commented on shardtree/src/lib.rs
>      pub fn witness_at_checkpoint_depth(
The depth query is kind of like an index query into a `Vec`, which for things like `Vec::get` return `None` on out-of-bounds queries. But in that case, querying an empty `Vec` is semantically equivalent to querying past the end of a non-empty `Vec`, whereas here I can kinda see the benefit of distinguishing "there is a witness at this depth, we just don't have information for it" vs "there is no possible witness at this depth" (i.e. any `depth >= tree_size`).

2024-09-27 14:47 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/incrementalmerkletree/compare/818941800e7553fbc86c8af1f7a31df20e18c695..9a77e51cc4c99feb6af3bd4146e505e2c70b6677) to address comments from code review.

2024-09-27 16:42 UTC, str4d approved these changes
utACK 9a77e51cc4c99feb6af3bd4146e505e2c70b6677 after doc fixes

2024-09-27 16:42 UTC, str4d commented on incrementalmerkletree-testing/src/lib.rs
> +    /// false if the tree would exceed the maximum allowed number of levels in the tree.
```suggestion
    /// Appends a new value to the tree at the next available slot.
    ///
    /// Returns true if successful and false if the tree would exceed
    /// the maximum allowed number of levels in the tree.
```

2024-09-27 16:42 UTC, str4d commented on shardtree/CHANGELOG.md
> +    now takes the `checkpoint_depth` argument as `Option<usize>` instead of
```suggestion
    now take their `checkpoint_depth` argument as `Option<usize>` instead of
```
or "now each take" if you want to match the language from the previous bulletpoint.

2024-09-27 16:42 UTC, str4d commented on shardtree/CHANGELOG.md
> +    `usize`. The semantics of this method are now changed such that if a
```suggestion
    `usize`. The semantics of these methods are now changed such that if a
```

2024-09-27 16:42 UTC, str4d commented on shardtree/CHANGELOG.md
> +    `Ok(None)` if no checkpoint was available at the given checkpoint depth.The
```suggestion
    `Ok(None)` if no checkpoint was available at the given checkpoint depth. The
```

2024-09-27 16:42 UTC, str4d commented on shardtree/CHANGELOG.md
> +    error is returned if no checkpoint exists at the given index. IT IS NO LONGER
This doesn't match the previous sentence, which says that `Ok(None)` is returned if no checkpoint was available at the given checkpoint depth. (Also they disagree on "depth" vs "index".)

2024-09-27 16:53 UTC, nuttycom commented on shardtree/CHANGELOG.md
> +    error is returned if no checkpoint exists at the given index. IT IS NO LONGER
```suggestion
    checkpoints of the tree in reverse order of checkpoint identifier. IT IS NO LONGER
```

2024-09-27 16:57 UTC, str4d approved these changes
Re-utACK 3f59900acf460af3e08a6ec503adf907ed9bb63b

2024-09-27 17:09 UTC, merged