Move common utilities to the incrementalmerkletree crate & turn into a workspace.
zcash/incrementalmerkletree pull request #49
Opened 2022-12-14 23:07 UTC by nuttycom

These changes are in preparation for the introduction of the `shardtree` crate, which provides an alternate Merkle tree implementation that allows out-of-order insertion.

2022-12-16 21:32 UTC, str4d commented on incrementalmerkletree/Cargo.toml
> +description = "Common types, interfaces, and utilities for Merkle tree data structures"
How big of a diff is this from `incrementalmerkletree 0.3.0`? I also now realise I was mistaken in thinking that any of the `incrementalmerkletree` crate releases ever provided the older interface that `zcash_client_backend` currently uses (which it instead gets from the tree implementation in `zcash_primitives`), so the "easy migration" pathway I had previously described doesn't really work. Perhaps we should move the older structures from `zcash_primitives` into this crate, even though they won't be used going forward?

2022-12-17 02:36 UTC, nuttycom commented on incrementalmerkletree/Cargo.toml
> +description = "Common types, interfaces, and utilities for Merkle tree data structures"
Yeah, moving those data structures here would make sense. This is a substantial diff from 0.3.0; basically everything was moved to the `bridgetree` crate already and we haven't released `incrementalmerkletree` since then. I wasn't sure whether I should create this as an entirely new crate or just reuse `incrementalmerkletree` since it's essentially abandonware otherwise.

2022-12-21 11:02 UTC, str4d requested changes
Reviewed 6ee1c4aa315a6d3196c3e3eff08839dd6eeca24b.

2022-12-21 11:04 UTC, str4d commented on bridgetree/CHANGELOG.md
> +  `incrementalmerkletree::testing`.
Ah, I see that it gets filled again later, and then at the end removed entirely. The commit in question could still be reworked, but it doesn't matter.

2022-12-21 19:04 UTC, nuttycom commented on incrementalmerkletree/src/lib.rs
> +pub use address::Position;
At the point, I think it makes sense to just get rid of the modules and move everything into the root.

2022-12-21 19:35 UTC, nuttycom commented on incrementalmerkletree/src/testing.rs
> +            .zip(
Come to think of it, I don't know why this is named `lazy_root` either; there's nothing lazy about it.

2022-12-21 19:41 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/incrementalmerkletree/compare/6ee1c4aa315a6d3196c3e3eff08839dd6eeca24b..f5193faf9133c995c485667612c1cba91c955336) to address suggested changes.

2022-12-21 22:19 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/incrementalmerkletree/compare/6ee1c4aa315a6d3196c3e3eff08839dd6eeca24b..0dde92c699b1aee88d27bd842c6bdadcf3bda081) to address suggested changes.

2023-01-05 20:16 UTC, ebfull approved these changes

2023-01-06 09:22 UTC, str4d approved these changes
utACK

2023-01-06 09:22 UTC, merged