Add `shardtree` crate.
zcash/incrementalmerkletree pull request #50
Opened 2022-12-15 18:03 UTC by nuttycom

This builds atop #49.

The `shardtree` crate implements a sparse, aggressively pruned Merkle tree that supports out-of-order insertion, witnessing of marked leaves, and truncation.

2023-01-12 19:17 UTC, nuttycom commented
Converting back to draft as I figured out a simpler way to approach truncation in root & witness calculation.

2023-03-01 23:05 UTC, softminus commented
It feels to me like there's a bit too much freedom the way the `PrunableTree` is defined:
```
type PrunableTree<H> = Tree<Option<Rc<H>>, (H, RetentionFlags)>;
```

since this means that leaf nodes (if the `Option` isn't a `None`) can have two (potentially different) values of type `H` (here, hashes), and this seems like it would be a significant pain to ensure that the obvious invariant of "the two hashes are always the same" always holds regardless of the tree operations.

Is there a way to use the type system to constrain `Leaf` nodes to only have one single value of type `H`?

2023-03-01 23:12 UTC, softminus requested changes

2023-03-03 21:52 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/incrementalmerkletree/compare/2494c3008687e5366019422eaaf2f55ff65ebc30..3b63465b3e42534b4da9888bf35af35ed7bd7d60) to prune the annotation state space to eliminate some invalid states.

2023-03-07 21:39 UTC, ebfull requested changes
First thorough review pass of the first several commits. It seems like a lot of stuff is ending up in the public API that I would think didn't need to be there ultimately, and it would perhaps be nicer to break some of the structures into separate submodules especially to help identify those cases.

2023-03-07 21:39 UTC, ebfull commented on shardtree/src/lib.rs
> +    ///   leaf values will be treated as `Nil`.
I think this doc comment is out of date. The parameter for this function is called `truncate_at`, and it doesn't sound like the return type matches the description.

2023-03-07 21:39 UTC, ebfull commented on shardtree/src/lib.rs
> +                left_incomplete.append(&mut right_incomplete);
The slightly more "correct" thing to do here is `left_incomplete.extend(right_incomplete);` which takes `right_incomplete` by value and doesn't require `right_incomplete` to be mutable.

2023-03-07 21:39 UTC, ebfull commented on shardtree/src/lib.rs
> +            xs.append(&mut ys);
`xs.extend(ys);` and `ys` does not need to be mutable.

2023-03-07 21:54 UTC, ebfull commented on shardtree/src/lib.rs
> +                left_incomplete.append(&mut right_incomplete);
Actually, I'm not sure that is actually a more correct way given Rust doesn't have specialization. It might actually be slower because `append` on `BTreeSet` can avoid iterating. Nevermind!

2023-03-07 23:13 UTC, softminus requested changes

2023-03-08 00:00 UTC, softminus requested changes

2023-03-08 00:37 UTC, nuttycom commented on shardtree/src/lib.rs
> +                    } else {
This case can no longer occur.

2023-03-08 00:38 UTC, nuttycom commented on shardtree/src/lib.rs
> +                    ann,
This possibility is no longer representable.

2023-03-08 00:39 UTC, nuttycom commented on shardtree/src/lib.rs
> +pub static MARKED: RetentionFlags = RetentionFlags(0b00000010);
`bitflags` looks nice, I didn't know that existed.

2023-03-08 18:14 UTC, nuttycom commented
[force-pushed](https://github.com/zcash/incrementalmerkletree/compare/d604ffc14a1ea2a8e4de2a900b12f6fdcb9de33a..fa7c6673fd18287789925f651cdeea473a7b2193) to address comments from review.

2023-03-08 18:17 UTC, nuttycom commented
> First thorough review pass of the first several commits. It seems like a lot of stuff is ending up in the public API that I would think didn't need to be there ultimately, and it would perhaps be nicer to break some of the structures into separate submodules especially to help identify those cases.

My general development philosophy, particularly when immutable data structures are concerned, is that one should make public all the operations that are possible to make public. If you have specific suggestions about things that you think are unsafe to have in the public API though, please make note of them.

2023-03-08 18:22 UTC, nuttycom commented on shardtree/src/lib.rs
> +pub static MARKED: RetentionFlags = RetentionFlags(0b00000010);
Do you think it's actually worth it to bring in the extra dependency? One of the things that I like about doing this manually is that the flags and the flag masks can have different types, with the relationships between those types correctly represented in the type system.

2023-03-08 18:22 UTC, nuttycom commented on shardtree/src/lib.rs
> +pub static MARKED: RetentionFlags = RetentionFlags(0b00000010);
I suppose that I could still create the separate mask types, but really the existing operations are all that we need.

2023-03-08 20:29 UTC, ebfull commented on shardtree/src/lib.rs
> +pub static MARKED: RetentionFlags = RetentionFlags(0b00000010);
I do think it's worth it because we already depend on it in our Rust tech stack in Zcash and it's a pretty common dependency in the Rust ecosystem.

2023-03-08 21:37 UTC, ebfull commented on shardtree/src/lib.rs
> +                value: value.clone(),
I think it'd be better for the reduction function to take `F: for<'a> Fn(Node<B, &'a A, &'a V>) -> B` instead so that you don't need to perform this clone or the clone of the annotation above, improving performance and reducing type restrictions.

2023-03-08 21:37 UTC, ebfull commented on shardtree/src/lib.rs
> +                value: value.clone(),
Same comment on the clone above.

2023-03-08 21:41 UTC, ebfull commented on shardtree/src/lib.rs
> +                (other, Tree(Node::Nil)) => Ok(other),
These can be merged together.

```suggestion
            (Tree(Node::Nil), other) | (other, Tree(Node::Nil)) => Ok(other),
```

2023-03-08 21:45 UTC, ebfull commented on shardtree/src/lib.rs
> +                }
These two cases can be merged together because they behave the same. Also, we can make the pattern match more exhaustive (and the code within more robust) by explicitly pattern matching on the `Node::Parent` case. (The Rust compiler doesn't actually "know" or remember the pattern match holds within the case body, which is annoying.)

```suggestion
               (Tree(Node::Leaf { value }), parent @ Tree(Node::Parent { .. }))
                | (parent @ Tree(Node::Parent { .. }), Tree(Node::Leaf { value })) => {
                    if parent
                        .root_hash(addr, no_default_fill)
                        .iter()
                        .all(|r| r == &value.0)
                    {
                        Ok(parent.reannotate_root(Some(Rc::new(value.0))))
                    } else {
                        Err(addr)
                    }
                }
```

2023-03-08 23:12 UTC, ebfull commented on shardtree/src/lib.rs
> +    // cap_cache: Tree<Option<Rc<H>>, ()>
Is this intended to be removed?

2023-03-08 23:24 UTC, nuttycom commented on shardtree/src/lib.rs
> +    // cap_cache: Tree<Option<Rc<H>>, ()>
It's more of a TODO to be implemented later.

2023-03-09 20:33 UTC, nuttycom commented on shardtree/src/lib.rs
> +    /// empty roots corresponding to later positions will be filled by [`H::empty_root`].
```suggestion
    /// This tree will be truncated to the `truncate_at` position, and then empty
    /// roots corresponding to later positions will be filled by [`H::empty_root`].
```

2023-03-09 20:35 UTC, nuttycom commented on shardtree/src/lib.rs
> +                            // it is located at `position + 1`.
```suggestion
                            // can fill it with the empty leaf, but only if we are truncating at
                            // a position to the left of the current position
```

2023-03-09 20:35 UTC, nuttycom commented on shardtree/src/lib.rs
> +    // cap_cache: Tree<Option<Rc<H>>, ()>
```suggestion
    // /// TODO: Add a tree that is used to cache the known roots of subtrees in the "cap" of nodes between
    // /// `SHARD_HEIGHT` and `DEPTH` that are otherwise not directly represented in the tree.  This
    // /// cache will be automatically updated when computing roots and witnesses. Leaf nodes are empty
    // /// because the annotation slot is consistently used to store the subtree hashes at each node.
    // cap_cache: Tree<Option<Rc<H>>, ()>
```

2023-03-16 21:33 UTC, softminus commented on shardtree/src/lib.rs
> +/// A left-dense, sparse binary Merkle tree of the specified depth, represented as a vector of
> left-dense

possibly remove this?

2023-03-16 21:33 UTC, softminus commented on shardtree/src/lib.rs
> +/// A left-dense, sparse binary Merkle tree of the specified depth, represented as a vector of
also "vector"

2023-03-16 21:33 UTC, softminus commented on shardtree/src/lib.rs
> +    /// A map from position to the count of checkpoints at this position.
correct comment re what maps to what

2023-03-16 21:33 UTC, softminus commented on shardtree/src/lib.rs
> +        C: Clone + Ord + core::fmt::Debug,
`Debug` isn't necessary here

2023-03-16 21:33 UTC, softminus commented on shardtree/src/lib.rs
> +                // clear the checkpoint leaf
maybe factor out this and the following for loop

2023-03-16 21:43 UTC, softminus commented on shardtree/src/lib.rs
> +                                        right.as_ref().clone(),
does the semantics of the `map_or_else` imply that `right` is going to be a Nil node? Should we add an assert here or something? Do we need to use `unite` at all?

2023-03-20 21:38 UTC, softminus commented
utACK given review comments

2023-03-21 22:50 UTC, softminus approved these changes
utACK pending changes

2023-03-23 18:23 UTC, ebfull approved these changes
ACK. I've done at least four passes and haven't found anything majorly concerning and the testing appears very thorough.

2023-03-23 18:23 UTC, ebfull commented on shardtree/src/lib.rs
> +    // cap_cache: Tree<Option<Rc<H>>, ()>
Generally speaking I'm not in favor of merging commented code that is not built / tested, but I won't oppose it in this case because it seems like we're on the path to implementing this next anyway.

2023-03-23 19:12 UTC, merged