Compute witnesses as of checkpoint depth rather than as of a root hash.
zcash/incrementalmerkletree pull request #52
Opened 2023-01-04 21:35 UTC by nuttycom

This builds atop #49

2023-01-09 20:11 UTC, nuttycom commented on bridgetree/src/lib.rs
> +    /// Removes the oldest checkpoin if there are more than `max_checkpoints`. Returns true if
```suggestion
    /// Removes the oldest checkpoint if there are more than `max_checkpoints`. Returns true if
```

2023-02-09 17:22 UTC, softminus commented on bridgetree/CHANGELOG.md
> +- `BridgeTree::witness` now takes a checkpoint depth rather than a root hash to
@nuttycom says this is so we restrict the domain of the witness-generation function to only work on end-of-block tree states (which correspond to the checkpoints), rather than any arbitrary root hash (which could refer to the state of the tree in the middle of a block).

2023-02-09 17:24 UTC, softminus commented on bridgetree/CHANGELOG.md
> +- `BridgeTree::witness` now takes a checkpoint depth rather than a root hash to
Also it makes this consistent between `BridgeTree` (what this is modifying) and `CompleteTree` (the reference implementation for tests).

2023-02-09 17:28 UTC, softminus commented on bridgetree/src/lib.rs
> -    is_marked: bool,
No longer necessary to store.

2023-02-09 17:33 UTC, softminus commented on bridgetree/src/lib.rs
> +    forgotten: BTreeSet<Position>,
The set of the positions of notes that were spent within the span of this checkpoint (after the checkpoint was made but before the next checkpoint)

2023-02-09 17:35 UTC, softminus commented on bridgetree/src/lib.rs
> +    forgotten: BTreeSet<Position>,
When we roll back to a checkpoint, we use the forgotten set to restore the set of previously (but will be rolled back!) spent nodes to be part of the set of marked leaves.

2023-02-09 17:47 UTC, softminus commented on bridgetree/src/lib.rs
>      fn rewrite_indices<F: Fn(usize) -> usize>(&mut self, f: F) {
We have a vector of bridges [A-to-B, B-to-C, C-to-D,...]. When we coalesce this to something like [A-to-C, C-to-D], we previously had to rewrite the usize values in the `forgotten: BTreeMap<Position, usize>`, but now that this is gone, we no longer need to.

2023-02-09 17:48 UTC, softminus commented on bridgetree/src/lib.rs
>      fn rewrite_indices<F: Fn(usize) -> usize>(&mut self, f: F) {
Here, `f` will subtract the number of bridges that have been removed via garbage collection.

2023-02-09 17:51 UTC, softminus commented on bridgetree/src/lib.rs
> +    checkpoints: VecDeque<Checkpoint>,
We remove them from the front (the oldest ones) as they fall out of the reorg boundary, and we remove them from the back (the most recently added ones) when there *is* a reorg.

2023-02-09 17:53 UTC, softminus commented on bridgetree/src/lib.rs
> +            checkpoints: VecDeque::from(vec![Checkpoint::at_length(0)]),
Always create a checkpoint when the tree is empty

2023-02-09 17:53 UTC, softminus commented on bridgetree/src/lib.rs
> +        assert!(max_checkpoints >= 1);
Usually the max_checkpoints will be 100, the reorg limit

2023-02-09 17:55 UTC, softminus commented on bridgetree/src/lib.rs
> +            for pos in c.forgotten.iter() {
When the checkpoint drops off, we actually remove (in our current tree) the marked nodes that were on the `forgotten` list for that checkpoint.

2023-02-09 17:57 UTC, softminus commented on bridgetree/src/lib.rs
> +    /// Marks the current leaf as one for which we're interested in producing a witness.
Current leaf = most recently added leaf

2023-02-13 17:19 UTC, softminus commented on bridgetree/src/lib.rs
> +            c.forgotten.insert(position);
Rather than removing it from the actual map and adding it to the `forgotten` map, it _only_ adds it to the `forgotten` map (actual removal happens when the checkpoint is removed).

2023-02-13 17:20 UTC, softminus commented on bridgetree/src/lib.rs
> +            c.forgotten.insert(position);
(not on garbage collection: garbage collection = traverse entire tree and fuse information we don't need anymore. checkpoint removal doesn't trigger a GC)

2023-02-13 17:20 UTC, softminus commented on bridgetree/src/lib.rs
> -                    .push(Checkpoint::at_length(self.prior_bridges.len(), is_marked));
this function's changes are just a carryover of the types change

2023-02-13 17:38 UTC, softminus commented on bridgetree/src/lib.rs
> +                .map(|b| b.successor(self.saved.contains_key(&b.position())));
Create a new successor bridge that starts on the previous one, using the `saved` map (_after_ removing the positions that were marked during the being-reverted checkpoint period).

`.successor` generates a new bridge, and its argument is true if the current node is one that's going to be tracked.

`.map(|b| b.successor(self.saved.contains_key(&b.position())))` operates over a _single_ item, and there's no `Vec` or anything like that, the type that's being mapped over is a `Maybe`.

`saved` map goes from marked node positions to the bridge that ends at that node's position -- since the beginning of time.

Each checkpoint can contain multiple bridges! So rewinds can discard multiple bridges.

Marking a node moves the current bridge to the frozen/immutable `prior_bridges` and creates a new mutable `current_bridge` starting at that position.

2023-02-13 17:41 UTC, softminus commented on bridgetree/src/lib.rs
> +        &self,
self=tree

2023-02-13 17:41 UTC, softminus commented on bridgetree/src/lib.rs
> +        checkpoint_depth: usize,
as of `checkpoint_depth` checkpoints back, give us the witness for the node at `position`

2023-02-13 17:45 UTC, softminus commented on bridgetree/src/lib.rs
> -            NotFound,
This PR removes the old functionality where you could pass in an arbitrary tree hash when asking the tree for a witness, so the `NotFound` case is no longer relevant -- `witness` is fed a checkpoint index.

2023-02-13 17:46 UTC, softminus commented on bridgetree/src/lib.rs
> -            });
Removed stuff tries to find a checkpoint with a matching tree hash.

2023-02-13 17:50 UTC, softminus commented on bridgetree/src/lib.rs
> +        let auth_base = if checkpoint_depth == 0 {
This will _not_ catch the case where the position we're told to generate a witness at has _never_ been marked!

2023-02-13 17:51 UTC, softminus commented on bridgetree/src/lib.rs
>              .ok_or(WitnessingError::PositionNotMarked(position))?;
`saved` map goes from marked node positions to the bridge that ends at that node's position -- since the beginning of time; so if it's not in that map, it's not saved and so we give `WitnessingError::PositionNotMarked(position)`

2023-02-13 17:52 UTC, softminus commented on bridgetree/src/lib.rs
>              .ok_or(WitnessingError::PositionNotMarked(position))?;
In a future commit, we can have the `saved` map lookup happen before the iteration over checkpoints.

2023-02-13 17:52 UTC, softminus commented on bridgetree/src/lib.rs
>              .ok_or(WitnessingError::PositionNotMarked(position))?;
So now we know it didn't get saved _after_ the checkpoint, and we know it got saved, so it has got to have been saved _before_ the checkpoint.

2023-02-15 17:08 UTC, softminus commented on bridgetree/src/lib.rs
> -            AuthBase::NotFound => {
`AuthBase` doesn't have a `NotFound` variant

2023-02-15 17:10 UTC, softminus commented on bridgetree/src/lib.rs
> -            // Get a list of the leaf positions that we need to retain. This consists of
We no longer need to regenerate this list of positions since it's directly out of `saved` with the new semantics.

2023-02-15 17:11 UTC, softminus commented on bridgetree/src/lib.rs
> -        fn witness(&self, position: Position, as_of_root: &H) -> Option<Vec<H>> {
Type changes

2023-02-15 17:12 UTC, softminus commented on bridgetree/src/lib.rs
> +        tree_mut.garbage_collect();
Check that garbage collection doesn't affect generated witnesses.

2023-02-15 17:15 UTC, softminus commented on bridgetree/src/lib.rs
> -            "Checkpoint drop is expected to succeed"
This test should be adapted to the new semantics for dropping the oldest checkpoint.

2023-02-15 17:16 UTC, softminus commented on bridgetree/src/lib.rs
> +        tree.garbage_collect();
We test to make sure the garbage collection doesn't prevent us from rewinding

2023-02-15 17:16 UTC, softminus commented on bridgetree/src/lib.rs
> +            .map(|pos| match t.witness(*pos, 0) {
New `witness` argument types

2023-02-15 17:17 UTC, softminus commented on bridgetree/src/lib.rs
> -    fn garbage_collect_idx() {
This got put in the start of the `garbage_collect` test

2023-02-15 17:25 UTC, softminus commented on bridgetree/src/lib.rs
> -            check_operations(tree, 4, &ops)?;
`DEPTH` method lets it figure out its own depth at runtime

2023-02-15 17:26 UTC, softminus commented on incrementalmerkletree/src/testing.rs
>      /// position or if the root does not correspond to a checkpointed
This is out of date -- witness doesn't take a root anymore!

2023-02-15 17:41 UTC, softminus commented on incrementalmerkletree/src/testing/complete_tree.rs
> +    leaves: Vec<Option<H>>,
Leaves being `Option<H>` will enable `shardtree` out of order testing -- not related to empty leaves

2023-02-15 17:42 UTC, softminus commented on incrementalmerkletree/src/testing/complete_tree.rs
> +    leaves: Vec<Option<H>>,
`None` represents lack of information about the leaf in question at that position

2023-02-27 23:06 UTC, softminus commented on incrementalmerkletree/src/testing.rs
>      /// position or if the root does not correspond to a checkpointed
Keep this comment since it's actual code review!!

2023-02-28 01:14 UTC, softminus requested changes
Untested ack, besides the two comments.

2023-02-28 01:14 UTC, softminus commented on incrementalmerkletree/src/testing.rs
>      /// Returns `None` if there is no available witness to that
```
/// Returns `None` if there is no available witness to that
/// position or if the root does not correspond to a checkpointed
/// root of the tree.
```
This comment is out of date, since `witness` doesn't take a root hash but instead a checkpoint depth index.

2023-02-28 01:14 UTC, softminus commented on bridgetree/src/lib.rs
> -    fn drop_oldest_checkpoint() {
I think this test can be adapted to the new semantics for dropping the oldest checkpoint.

2023-02-28 01:25 UTC, softminus requested changes
saw a second occurrence of the `witness` comment needing to be changed, and I don't think I can append it to the review, so here goes a second review

2023-02-28 01:25 UTC, softminus commented on bridgetree/src/lib.rs
>      /// Returns `None` if there is no available witness to that
Likewise, this comment should be changed to not refer to a `root` since the argument type has changed.

2023-03-04 00:04 UTC, nuttycom commented on bridgetree/src/lib.rs
> -    fn drop_oldest_checkpoint() {
I looked at this and it cannot, because it's no longer possible to produce a tree state where `drop_oldest_checkpoint` can succeed, because in order to create such a state you have to call `checkpoint`, which calls `drop_oldest_checkpoint` when `max_checkpoints` is exceeded. So the `drop_oldest_checkpoint` function is now just an internal implementation detail of the `checkpoint` function, and can't be tested independently.

2023-03-04 00:08 UTC, softminus approved these changes
utACK (previous review comments were addressed with the added commit).

2023-03-04 00:11 UTC, softminus commented on bridgetree/src/lib.rs
> -    fn drop_oldest_checkpoint() {
That makes sense; thanks for looking into it!

2023-03-07 19:09 UTC, ebfull approved these changes

2023-03-07 19:11 UTC, merged