Use witness for checkpointing
zcash/incrementalmerkletree pull request #7
Opened 2021-07-16 20:40 UTC by nuttycom

This extends from #6

2021-07-29 17:00 UTC, daira commented on src/bridgetree.rs
> +    pub fn value(&self) -> Option<&NonEmptyFrontier<H>> {
Should this not have a doc comment?

2021-07-29 17:01 UTC, daira commented on src/bridgetree.rs
> +/// position. Then, the authentication path may be completed by hashing any
This comment seems to be incomplete.

2021-07-29 17:03 UTC, daira commented on src/bridgetree.rs
> +    /// not perform any meaningful validation that the provided values
Double negative?

2021-07-29 17:06 UTC, daira commented on src/lib.rs
> +/// A type-safe wrapper for indexing into "levels" of a binary tree, such that
```suggestion
/// A type-safe wrapper for indexing into "altitudes" of a binary tree, such that
```

2021-07-29 17:06 UTC, daira approved these changes
utACK (modulo conflicts) with minor comments.

2021-08-03 13:26 UTC, str4d commented
Needs rebase now that #6 has merged.

2021-09-14 15:42 UTC, ebfull requested changes

2021-09-14 15:42 UTC, ebfull commented on src/bridgetree.rs
> +    //}
This test should be uncommented or removed.

2021-12-01 18:18 UTC, str4d commented on src/bridgetree.rs
> +                // Do not rewind if doing so would remove a witness.
This seems like incorrect behaviour to me. If we are rewinding to a checkpoint, that corresponds to "un-appending" from the incremental Merkle tree, which implies that whatever we were witnessing beyond that checkpoint no longer exists in the tree and cannot be witnessed.

2021-12-01 18:18 UTC, str4d commented on src/bridgetree.rs
> +                        // affect the successor bridge
This is implicitly referring to the fact that rewinding to a checkpoint drops that checkpoint from the list, so someone that wants to rewind to the same block height multiple times (like `zcashd` during repeated reorgs) will need to remember to call `.checkpoint()` immediately after `.rewind()`.

Similarly, if I call `.checkpoint()`, append commitments from a block, call `.checkpoint()` again, and then immediately call `.rewind()` (because the block is immediately reorged away), I would expect to be rolled back to the first checkpoint, but the current code treats `.checkpoint().rewind()` as a no-op, so leave the `BridgeTree` in a state where we have one checkpoint, plus the commitments from the now-reorged block, but no checkpoint for that block.

2021-12-02 14:08 UTC, nuttycom commented on src/bridgetree.rs
> +                // Do not rewind if doing so would remove a witness.
We confirmed that this was intended behavior in pairing with @ebfull.

2021-12-09 23:13 UTC, daira commented on src/bridgetree.rs
> +        next.map(|(leaf, succ)| {
Wouldn't it be clearer to use ? here, e.g.:
```
        let current = self.bridges.last()?;
        let leaf = current.leaf_value().clone();
        let blen = self.bridges.len();
        let succ = current.successor(blen - 1);
```

2021-12-09 23:16 UTC, nuttycom commented on src/bridgetree.rs
> +        next.map(|(leaf, succ)| {
Yeah, I guess that'd be the idiomatic Rust solution.

2021-12-09 23:18 UTC, daira approved these changes
utACK

2021-12-09 23:23 UTC, nuttycom commented on src/bridgetree.rs
> +        next.map(|(leaf, succ)| {
Oh, I remember why I did it this way now. It's that `self.bridges.last()?` immutably borrows `self.bridges` for the entire scope, and you then can't get the mutable borrow you need to push to it.

2021-12-09 23:26 UTC, nuttycom commented on src/bridgetree.rs
> +        next.map(|(leaf, succ)| {
That's also the reason why I do this weird `let next = ...` and then `next.map` rather than doing everything in the scope of the single `map` call.

2021-12-10 12:43 UTC, str4d approved these changes
utACK 0a8854f1b0885dd86cac502397e42b0f74b7d963

2021-12-10 12:43 UTC, str4d commented on src/bridgetree.rs
> +    pub fn frontier(&self) -> Option<&NonEmptyFrontier<H>> {
Document this. Non-blocking; there are a bunch of other APIs that also need documentation, so we should just have a separate PR for all of them.

2021-12-10 17:32 UTC, merged