shardtree: Add the ability to avoid pruning specific checkpoints.
zcash/incrementalmerkletree pull request #95
Opened 2024-01-19 19:29 UTC by nuttycom

2024-01-19 20:34 UTC, str4d requested changes
Reviewed 34b1a5f704719436f436d0c8275c63e03942bce5.

2024-01-19 20:34 UTC, str4d commented on shardtree/src/lib.rs
> +    /// across pruning operations.
This API needs a bit more documentation, because it is unclear whether or not this data being stored in `ShardTree` means it needs to be serialized. In particular, we should document that this API needs to be called after constructing `ShardTree` but before calling any methods that take `&mut self` (or whatever other criterion gates potential pruning). An example would be ideal:
```suggestion
    /// Adds the provided checkpoint to the set of checkpoints to be retained
    /// across pruning operations.
    ///
    /// TODO: A bit more documentation.
    ///
    /// # Examples
    ///
    /// ```
    /// use incrementalmerkletree::Retention;
    /// use shardtree::ShardTree;
    ///
    /// # fn load_shardtree_from_disk() -> ShardTree<SomeShardStore> {
    /// #     todo!("Kris returns something useful for testing here.")
    /// # }
    /// # fn checkpoints_to_retain() -> Vec<SomeCheckpointId> {
    /// #     vec![] // TODO: Return something useful for testing here.
    /// # }
    /// # fn get_next_leaf() -> SomeLeafType {
    /// #     todo!("Kris returns something useful for testing here.")
    /// # }
    /// # fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// let mut tree = load_shardtree_from_disk();
    ///
    /// // The required checkpoints are stored separately from the tree.
    /// for checkpoint_id in checkpoints_to_retain() {
    ///     tree.ensure_retained(checkpoint_id);
    /// }
    ///
    /// // Now perform operations that might prune the tree.
    /// tree.append(get_next_leaf(), Retention::Ephemeral)?;
    /// # Ok(())
    /// # }
    /// ```
```

2024-01-19 20:34 UTC, str4d commented on shardtree/src/lib.rs
>              self.max_checkpoints,
Update this trace to mention `self.to_retain.len()`.

2024-01-19 20:34 UTC, str4d commented on shardtree/src/lib.rs
> +        if checkpoint_count > retain_count {
This doesn't match my intuition. I expected that only checkpoints in `self.to_retain` that fall outside the range of `self.max_checkpoints` would increase the cap. Instead, this excludes all explicitly-retained checkpoints from the cap, leading to (in the context of Zcash) older checkpoint heights being retained than is necessary.

I don't particularly mind doing it this way if it makes the implementation easier, but a) we should explicitly decide which way we want to go (as I disagree with us changing the behaviour of the new API later in a non-compilation-breaking way; going from the current implementation to the one matching my intuition would constitute data loss to someone depending on the current behaviour), and b) we should document it on `ShardTree::ensure_retained`.

2024-01-19 20:34 UTC, str4d commented on shardtree/src/lib.rs
> +                        checkpoints_to_delete.len() < remove_count && !self.to_retain.contains(cid);
Does the `clear_at` closure below behave correctly after this change? Its current implementation at a glance appears to assume that we only have a single transition from `removing = true` to `removing = false` when iterating in ascending order through the checkpoints (because it treats `removing = false` as a fixup operation, but `removing = true` as unconditional). We can now have arbitrarily many transitions between those two states, up until we reack the `self.max_checkpoints` boundary.

2024-01-19 20:34 UTC, str4d commented on shardtree/src/lib.rs
> +        );
Add a test case where we request to retain a checkpoint that is within the range of checkpoints that would already be retained. This is to exercise the `self.max_checkpoints + self.to_retain.len()` behaviour I questioned above; we should have a case that checks whichever behaviour we go with.

2024-01-19 20:57 UTC, nuttycom commented on shardtree/src/lib.rs
> +        if checkpoint_count > retain_count {
The reason to retain all the checkpoints is so that the 100-block rollback limit is matched by the number of checkpoints to which you can rewind, because we use checkpoints not just for witnessing but for rewinds.

2024-01-19 20:58 UTC, nuttycom commented on shardtree/src/lib.rs
> +                        checkpoints_to_delete.len() < remove_count && !self.to_retain.contains(cid);
Yes, I believe so. Essentially, the `else` branch only becomes relevant when some prior iteration of the loop has removed data that needs to be restored, and what we're doing in this PR is explicitly skipping over some of those removals.

2024-01-19 21:03 UTC, nuttycom commented on shardtree/src/lib.rs
> +        if checkpoint_count > retain_count {
I guess that since checkpoint identifiers are intended to be totally ordered, we could partition the set of retained checkpoints and then on each iteration, check whether we're down to the max number of checkpoints, not counting the number of earlier retained checkpoints. That might be okay.

2024-01-19 21:19 UTC, nuttycom commented on shardtree/src/lib.rs
> +    /// across pruning operations.
Hm, I guess maybe I should actually add this to the `ShardStore` interface, so that it's up to the implementer of that to decide whether or not the explicitly retained items are represented in the serialization. In the `zcash_client_sqlite` database, they'll actually be serialized; the retained checkpoint identifier will always be the block height prior to the earliest unscanned `FoundNote` or `ChainTip` range, and each time we go to perform a `put_blocks` operation, we'll check whether the operation has increased that height. 

It gets a little complicated, because `Historic` and `OpenAdjacent` scanning can find notes at _lower_ heights than the current "high water mark" - in the event that that happens, the value of those notes can't be added to the available balance until their entire subtrees are scanned. This leads to an uncomfortable situation where you might be able to increase the available balance if you were to choose a _lower_ checkpoint height, for example if you have a small spendable note at the chain tip, but then discover a large spendable note at a lower height.

2024-01-19 21:57 UTC, nuttycom commented on shardtree/src/lib.rs
> +        if checkpoint_count > retain_count {
Aha. The better way to do this is, instead of `max_checkpoints`, it should be `min_checkpoints_to_retain`. That would also allow the implementation to skip pruning entirely sometimes in order to batch pruning operations and so forth, and better reflects the semantics we actually want.

2024-06-28 20:12 UTC, daira commented on shardtree/src/lib.rs
> +    /// The minumum number of checkpoints to retain when pruning.
```suggestion
    /// The minimum number of checkpoints to retain when pruning.
```

2024-06-28 20:13 UTC, daira commented on shardtree/src/lib.rs
> +    pub fn new(store: S, min_checkpoints_to_retain: usize) -> Self {
This seems quite a significant semantic change for something that retains the same type signature. Is it the case that previous callers will be correct for the new semantics? In any case please document the parameter.

2024-06-28 20:21 UTC, daira approved these changes
utACK with comments.

2026-06-30 19:18 UTC, nuttycom commented
Superseded by #184, which reaches the same explicit-checkpoint-retention design rebased onto current `main` and simplified — record retention is decoupled from leaf marking via `ShardTree::ensure_retained`, and no `Reference`/`Marking` changes are required (the retained checkpoint's own `CHECKPOINT` retention protects the witness-supporting nodes). Closing in favor of #184.

— Closed with Claude Code assistance.

2026-06-30 19:18 UTC, closed without merging